spring:
  datasource:
    #url: jdbc:h2:mem:cervejaria
    url: jdbc:postgresql://10.111.172.37:5432/acme
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 10.105.145.75
      port: 6379
      timeout: 1800
      repositories:
        enabled: true
server:
  port: 8091
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
