global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "redis"
    static_configs:
      - targets: ["host.docker.internal:30007"]
        labels:
          app: "redis"
  - job_name: "postgres"
    static_configs:
      - targets: [ "host.docker.internal:30008" ]
        labels:
          app: "postgres"
  - job_name: "app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:30010" ]
        labels:
          app: "front"


      