apiVersion: v1
kind: Service
metadata:
  name: banco-monitoramento-service
  namespace: cervejaria
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
      nodePort: 30008
  type: NodePort
  