name: Deploy to prod
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Verificar versões da JVM e Maven
        run: |
            java -version
            mvn -version
      - name: Limpar diretorio
        run: mvn clean
      - name: Executar Testes
        run: mvn test
      - name: Gerar pacote
        run: mvn package -DskipTests



